###############################################################
# Copyright (c) 2024 BMW Group AG
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.int.catena-x.net"
  tls:
    - secretName: "dim.int.catena-x.net-tls"
      hosts:
        - "dim.int.catena-x.net"
  hosts:
    - host: "dim.int.catena-x.net"
      paths:
        - path: "/api/dim"
          pathType: "Prefix"
          backend:
            port: 8080

dim:
  swaggerEnabled: true
  rootDirectoryId: "27fee02a-e265-4cfc-af70-4f217a33840b"
  operatorId: "27fee02a-e265-4cfc-af70-4f217a33840b"

migrations:
  logging:
    default: "Debug"

processesworker:
  logging:
    default: "Debug"
  dim:
    adminMail: "phil.schneider@digitalnativesolutions.de"
    clientIdCisCentral: "<path:portal/data/dim/int/dim#cisClientId>"
    clientSecretCisCentral: "<path:portal/data/dim/int/dim#cisClientSecret>"
    authUrl: ""
  subaccount:
    # -- Url to the subaccount service api
    baseUrl: "https://accounts-service.cfapps.eu10.hana.ondemand.com"
  entitlement:
    # -- Url to the entitlement service api
    baseUrl: "https://entitlements-service.cfapps.eu10.hana.ondemand.com"
  cf:
    clientId: "<path:portal/data/dim/int/cf#clientId>"
    clientSecret: "<path:portal/data/dim/int/cf#clientSecret>"
    tokenAddress: "https://login.cf.eu10.hana.ondemand.com/oauth/token"
    # -- Url to the cf service api
    baseUrl: "https://api.cf.eu10.hana.ondemand.com"
    grantType: "client_credentials"
  callback:
    scope: "openid"
    grantType: "client_credentials"
    # -- Provide client-id for callback.
    clientId: "<path:portal/data/dim/callback#clientId>"
    # -- Client-secret for callback client-id. Secret-key 'callback-client-secret'.
    clientSecret: "<path:portal/data/int/iam/centralidp-client-secrets#dim-portal-sa>"
    tokenAddress: "http://centralidp.int.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
    # -- Url to the cf service api
    baseAddress: "https://portal-backend.int.catena-x.net"
  technicalUserCreation:
    encryptionConfigs:
      index0:
        encryptionKey: "<<path:portal/data/dim/int/technicaluser#technicalusercreation-encryption-key0>"

idp:
  address: "https://centralidp.int.catena-x.net"
  jwtBearerOptions:
    tokenValidationParameters:
      validAudience: "DIM-Middle-Layer"

replicaCount: 2

postgresql:
  architecture: "standalone"
  auth:
    postgrespassword: "<path:portal/data/dim/int/postgres#postgres-password>"
    password: "<path:portal/data/dim/int/postgres#password>"
